"""
support interface list for stockx as below:
https://collector-px16ud0kof.cl6.perimeterx.net/api/v1/collector/mobile
https://collector-px16ud0kof.cl6.perimeterx.net/api/v1/collector/mobile
https://gateway.stockx.com/api/v3/browse?page={}&_search={}&dataType=product&currency=USD&country=HK
https://gateway.stockx.com/api/v2/products/{product_uuid}/activity?
https://gateway.stockx.com/api/v3/rowse?page={}&sort={}&order=DESC&browseVerticals=sneakers&dataType=product&currency=USD&country=HK&filterVersion=2
https://gateway.stockx.com/api/v3/rowse?page={}&shoeSize={}&_tags={}&gender={}&market.lowestAsk={}&year={}&productCategory=SNEAKERS&currency=USD&country=HK
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/v1/users/me?meta=include
https://gateway.stockx.com/api/v2/portfolioItems/{}?includes=payment,payout,pricing,shipping,product,meta,market&country=HK
https://accounts.stockx.com/oauth/token
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/v1/portfolio/multi?a=ask
https://gateway.stockx.com/api/v1/portfolio?a=ask
https://gateway.stockx.com/api/v1/portfolio/multi?a=ask
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/graphql
https://gateway.stockx.com/api/v1/portfolio?a=ask
https://gateway.stockx.com/api/v1/customers/{customer_id}
https://gateway.stockx.com/api/v1/portfolio/{chain_id}
https://gateway.stockx.com/api/graphql
"""